version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actualite_php
    working_dir: /var/www/html
    ports:
      - "8000:80"  # Apache écoute sur 80 dans le container
    volumes:
      - ./:/var/www/html  # Monte ton projet dans le container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: site_actus
      DB_USER: root
      DB_PASS: root

  mysql:
    image: mysql:8.0
    container_name: actualite_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site_actus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script/28-03-2026/script_v1.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./script/28-03-2026/test_data_1.sql:/docker-entrypoint-initdb.d/02-data.sql
      - ./script/28-03-2026/V6__add_all_indexes.sql:/docker-entrypoint-initdb.d/04-add-all-indexes.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: