SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE article_tag;
TRUNCATE TABLE collaboration;
TRUNCATE TABLE histo_status;
TRUNCATE TABLE hito_publication;
TRUNCATE TABLE Media;
TRUNCATE TABLE Article;
TRUNCATE TABLE status_article;
TRUNCATE TABLE tag;
TRUNCATE TABLE type_media;
TRUNCATE TABLE Categorie;
TRUNCATE TABLE User_;
TRUNCATE TABLE Role;

SET FOREIGN_KEY_CHECKS = 1;

-- 2️⃣ Réinitialiser les auto-incréments
ALTER TABLE Role AUTO_INCREMENT = 1;
ALTER TABLE User_ AUTO_INCREMENT = 1;
ALTER TABLE Categorie AUTO_INCREMENT = 1;
ALTER TABLE type_media AUTO_INCREMENT = 1;
ALTER TABLE tag AUTO_INCREMENT = 1;
ALTER TABLE status_article AUTO_INCREMENT = 1;
ALTER TABLE Article AUTO_INCREMENT = 1;
ALTER TABLE Media AUTO_INCREMENT = 1;
ALTER TABLE hito_publication AUTO_INCREMENT = 1;
